apiVersion: v1
kind: Namespace
metadata:
  name: logto
---
apiVersion: v1
kind: Secret
metadata:
  name: logto-secrets
  namespace: logto
type: Opaque
stringData:
  NODE_TLS_REJECT_UNAUTHORIZED: "0"
  TRUST_PROXY_HEADER: "true"
  DB_URL: "postgres://postgres:admin@192.168.101.29:5432/logto"
  ENDPOINT: "https://dev-api-logto.kfc.com.ec"
  ADMIN_ENDPOINT: "https://dev-logto.kfc.com.ec"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logto-app
  namespace: logto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logto-app
  template:
    metadata:
      labels:
        app: logto-app
    spec:
      hostAliases:
        - ip: 34.54.130.27
          hostnames:
            - apilogto.kfc.com.ec
            - logto.kfc.com.ec
      containers:
        - name: logto-app
          image: us-east1-docker.pkg.dev/grupo-kfc-poc/registrykfc/logtokfc:latest
          imagePullPolicy: Always
          command: ["sh", "-c"]
          args:
            - "npm run cli db seed -- --swe && npm start"
          ports:
            - containerPort: 3001
            - containerPort: 3002
          envFrom:
            - secretRef:
                name: logto-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: logto-service
  namespace: logto
  annotations:
    cloud.google.com/backend-config: '{"ports": {"3002":"logto-gateway-status", "3001":"logto-gateway-status"}}'
    cloud.google.com/neg: '{"ingress":true}'
spec:
  selector:
    app: logto-app
  ports:
    - protocol: TCP
      name: http-3001
      port: 3001
      targetPort: 3001
    - protocol: TCP
      name: http-3002
      port: 3002
      targetPort: 3002
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: logto-service-ingress
  namespace: logto
  annotations:
    kubernetes.io/ingress.class: gce
    ingress.gcp.kubernetes.io/pre-shared-cert: kfc-ecuador-24-25
spec:
  rules:
    - host: logto.kfc.com.ec
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: logto-service
                port:
                  number: 3002
    - host: apilogto.kfc.com.ec
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: logto-service
                port:
                  number: 3001
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: logto-gateway-status
  namespace: logto
spec:
  healthCheck:
    port: 3002
    requestPath: /api/status
    timeoutSec: 3
    type: HTTP